<?php $paymentMethods = $this->getPaymentMethod(); ?>
<style>
    table tr td:first-child {
        width: 250px;
    }
    table#transactions_details {
        border-collapse: collapse; 
    }
    table#transactions_details tr.top  {
        border-top: 1px solid black;
    }
    table#transactions_details tr.bottom {
        border-bottom: 1px solid black;
    }
</style>
<form id="form_create" action="<?php echo Mage::getUrl('stubs/payment/createPost') ?>" method="post">
    <table>
        <tr>
            <td><label for="timeout_duration">Timeout Duration</label></td>
            <td><input type="text" id="timeout_duration" name="timeout_duration" /></td>
        </tr>
        <tr>
            <td><label for="need_transfer">Need Transfer (Kasad/Donatur)</label></td>
            <td><input type="checkbox" id="need_transfer" name="need_transfer" /></td>
        </tr>
        <tr>
            <td><label for="callbacks_id">Callbacks - Stub's Param ID</label></td>
            <td>
                <input type="text" id="callbacks_id" name="callbacks_id" />
                <button type="button" id="callbacks_id_random">Generate</button>
            </td>
        </tr>
    </table>
    <br />
    <table>
        <tr>
            <td><label for="payer_method">Payer Method</label></td>
            <td>
                <select id="payer_method" name="payer_method">
                    <?php
                    foreach ($paymentMethods as $method => $fields) {
                        echo "<option value='$method'>" . ucwords($method) . "</option>";
                    }
                    ?>
                </select>
            </td>
        </tr>
    </table>
    <table id="payer_details">
    </table>
    <br />
    <b>Transactions</b>
    <table id="transactions_details" cellspacing="0">
    </table>
    <br />
    <div id="transactions_buttons">
        <button type="button" id="add_transaction">Add Transaction</button>
        <button type="button" id="delete_transaction">Delete Transaction</button>
    </div>
    <br />
    <input type="submit" value="Create Payment" />
</form>

<script type="text/javascript">
    var dataPayerMethod = {};
    <?php foreach ($paymentMethods as $method => $fields) { ?>
        dataPayerMethod["<?php echo $method;?>"] = new Array(<?php echo count($fields); ?>);
        <?php $i = 0; ?>
        <?php foreach ($fields as $field => $fieldDescription) { ?>
            dataPayerMethod["<?php echo $method;?>"][<?php echo $i; ?>] = {};
            dataPayerMethod["<?php echo $method;?>"][<?php echo $i; ?>]["name"] = "<?php echo $field ;?>";
            dataPayerMethod["<?php echo $method;?>"][<?php echo $i; ?>]["type"] = "<?php echo $fieldDescription['type'] ;?>";
            dataPayerMethod["<?php echo $method;?>"][<?php echo $i; ?>]["field"] = "<?php echo implode(',', $fieldDescription['field']) ;?>";
            <?php $i++; ?>
        <?php } ?>
    <?php } ?>

    var currencies = [<?php echo $this->implodeCommaAndQuote($this->getCurrencies()); ?>];
    var transactionTypes = [<?php echo $this->implodeCommaAndQuote($this->getTransactionTypes()); ?>];

    function toTitleCase(str) {
        return str.replace(/\w\S*/g, function(txt){return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();});
    }

    function replaceAll(find, replace, str) {
        return str.replace(new RegExp(find, 'g'), replace);
    }

    function changePayerMethod(dataPayerMethod) {
        var selected = $("#payer_method").find(":selected").val();
        $("#payer_details").empty();
        for (var i = 0; i < dataPayerMethod[selected].length; i++) {
            var tr = "<tr>";
            tr += "<td><label for='" + dataPayerMethod[selected][i]["name"] + "'>" + toTitleCase(replaceAll("_", " ", dataPayerMethod[selected][i]["name"])) + "</label></td>";
            if (dataPayerMethod[selected][i]["type"] == "select") {
                tr += "<td>";
                tr += "<select id='" + dataPayerMethod[selected][i]["name"] + "' name='payer_detail_" + dataPayerMethod[selected][i]["name"] + "'>";
                var fields = dataPayerMethod[selected][i]["field"].split(",");
                for (var i = 0; i < fields.length; i++) {
                    tr += "<option value='" + fields[i] + "'>" + fields[i] + "</option>";
                }
                tr += "</select>";
                tr += "</td>";
            } else {
                tr += "<td><input type='text' id='" + dataPayerMethod[selected][i]["name"] + "' name='payer_detail_" + dataPayerMethod[selected][i]["name"] + "' /></td>";
            }
            tr += "</tr>";
            $("#payer_details").append(tr);
        }
    }

    function addTransactionRow() {
        var tr = "";
        tr = "<tr class='top'>";
        tr += "<td>Amount</td>";
        tr += "<td><input type='text' id='amount[]' name='amount[]' /></td>";
        tr += "</tr>";
        tr += "<tr>";
        tr += "<td>Currency</td>";
        tr += "<td><select name='currency[]'>";
        for (var i = 0; i < currencies.length; i++) {
            tr += "<option value='" + currencies[i] + "'>" + currencies[i] + "</option>";
        }
        tr += "</select></td>";
        tr += "</tr>";
        tr += "<tr>";
        tr += "<td>Type</td>";
        tr += "<td><select name='transaction_type[]'>";
        for (var i = 0; i < transactionTypes.length; i++) {
            tr += "<option value='" + transactionTypes[i] + "'>" + transactionTypes[i] + "</option>";
        }
        tr += "</select></td>";
        tr += "</tr>";
        tr += "<tr class='bottom'>";
        tr += "<td>Description</td>";
        tr += "<td><input type='text' id='description[]' name='description[]' /></td>";
        tr += "</tr>";
        $("#transactions_details").append(tr);
    }

    function deleteTransactionRow() {
        $("#transactions_details tr:last").remove();
        $("#transactions_details tr:last").remove();
        $("#transactions_details tr:last").remove();
        $("#transactions_details tr:last").remove();
    }

    function randomString(length) {
        var chars = '0123456789'.split('');
        var str = '';
        for (var i = 0; i < length; i++) {
            str += chars[Math.floor(Math.random() * chars.length)];
        }
        return str;
    }

    $("#payer_method").change(function() {
        changePayerMethod();
    });
    $("#add_transaction").click(function() {
        addTransactionRow();
    });
    $("#delete_transaction").click(function() {
        deleteTransactionRow();
    });
    $("#callbacks_id_random").click(function() {
        $("#callbacks_id").val(randomString(5));
    })

    changePayerMethod(dataPayerMethod);
    addTransactionRow();
</script>