<h1>COMMON</h1>
<ul>
    <li><a id="link_oauth" href="<?php echo Mage::getUrl('stubs/oauth/key') ?>">Set OAuth Key</a></li>
    <li><a id="link_callbacks" href="<?php echo Mage::getUrl('stubs/callbacks/show') ?>">Show Callback Statistics</a></li>
</ul>

<h1>API ACCESS</h1>
<ul>
    <li><a id="link_payment_create" href="<?php echo Mage::getUrl('stubs/payment/create') ?>">Create Payment</a></li>
    <li><a id="link_payment_inquiry" href="<?php echo Mage::getUrl('stubs/payment/inquiry') ?>">Request Inquiry</a></li>
    <li><a id="link_payment_inquiries" href="<?php echo Mage::getUrl('stubs/payment/inquiries') ?>">Request Inquiry by Field</a></li>
    <li><a id="link_payment_state" href="<?php echo Mage::getUrl('stubs/payment/state') ?>">Change Payment State</a></li>
</ul>

<h1>BANK GATEWAY</h1>
<ul>
    <li><a id="link_bank_gateway_klikbca" href="<?php echo Mage::getUrl('stubs/klikbca') ?>">Klikbca</a></li>
</ul>

<h1>MERCHANT</h1>
<ul>
    <li><a id="link_payment_create" href="<?php echo Mage::getUrl('stubs/merchant') ?>">Merchant</a></li>
</ul>